## JulialearnProject
개꿀잼 Julia를 배워보자

### 출력과 자료형

In [1]:
# 출력
println("Hello, Sans!")

# 연산자
println(1+2)
println(3-1)
println(4*7)
println(3/2)
println(13÷4) # \div : ÷
println(13%4)
println(6^2)

Hello, Sans!
3
2
28
1.5
3
1
36

In [2]:
println(typeof(1_000_00))  # 나중에 확인
println(typeof(1.0))
println(typeof('a')) # like C
println(typeof("a"))
println(typeof("ㅇㅅㅇ"))


Int64
Float64
Char
String


String


### 변수와 표현식

In [3]:
π_val = 1.2 # \pi : π
❤ = 2
println(π_val)
println(❤) # emoji lol

1.2
2


In [4]:
println("홍진호"*"홍진호") # 문자열에서는 * 와 ^
println("홍진호"^2)

홍진호홍진호
홍진호홍진호


### 함수

In [5]:
println(parse(Int64, "0"))
# pritln(int(32)) Not python lol

println(parse(Float64, "0"))
println(Float64(0))
println(typeof(Float64(0))) # 실제 형태를 직접 함수로 사용 가능

println(trunc(Int64, 3.999))
println(trunc(3.99)) # 그냥 소수점을 없애기
println(floor(-4.11)) # 가우스 함수
println(typeof(trunc(3.9)))

# 많은 함수들은 Int64, Float64으로 처리되는 듯
# 왠만하면 그냥 둬도 될거 같다

0
0.0
0.0
Float64
3
3.0
-5.0


Float64


In [6]:
# 보충
println(typeof(Int(1.00))) # 64bit 프로그램을 사용해서 Int와 Int64가 동일 (Int64로 통일하자!)
println(Int64('❤')) # Char에서는 아스키 코드 반환
println(parse(Int64, "12"), "\n") # String에서 int로 바꾸려면 parse

println(typeof(float(2f-3))) # Float32은 f
println(typeof(float(2e-3))) # Float64은 e
println(typeof(Float64(2f-3))) # 형식 지정
# flaot은 자료형이 아니라 부동소수점으로 바꿔주는 함수 => 앞에 대문자가 아니다
println(parse(Float64, "12")) # String에서 float도 parse

Int64
10084
12

Float32
Float64
Float64
12.0

In [7]:
# Julia는 매우 수학적인 언어; 따라서, 삼각함수는 라디안 값을 받는다.
println(sin(2*π)) # 부동소수점 오류
println(sinpi(2)) # 대체제

println(sinpi(0.25))
println(sqrt(2)/2)

print(exp(1))

-2.4492935982947064e-16
0.0
0.7071067811865476
0.7071067811865476
2.718281828459045

In [8]:
function sans()
    println("와 샌즈다","!"^3)
end

function 홍진호()
    sans()
    sans()
end

홍진호()

와 샌즈다!!!
와 샌즈다!!!


In [9]:
println(sans())
println(typeof(sans())) # nothing은 문자열이 아니라 고유의 자료형인 'Nothing'을 가지고 있다.

와 샌즈다!!!
nothing
와 샌즈다!!!
Nothing

In [10]:
print("와 샌즈다 ") # print는 println의 엔터가 없는 형태이다
print("와 샌즈다 ")

와 샌즈다 와 샌즈

다 

### 조건과 재귀

In [11]:
m = 105
println(m / 60)
println(m ÷ 60)
println(m % 60)

1.75
1


45


In [12]:
x = 4
if x % 2 == 1 # x % 2 (X) Bool(x%2) (O)
    println("odd")
else
    println("even")
end

even


In [11]:
x = 2
if 0 ≤ x ≤ 5 # 0 <= x && x <= 5
    println("ㅇㅅㅇ")
elseif x < 0
    println("ㅇㅅㅇ;;")
elseif x ≠ -1 # x != -1
    println("ㅇㅅㅇ...")
end


ㅇㅅㅇ

In [14]:
# print("주어진 값은 : "); t = parse(Int64, readline()) # python의 input과 동일
# println(t)
# Jupyter 버그로 에러남

In [15]:
# 재귀함수
function iterstring(s, n)
    if n ≤ 0
        return
    end

    print(s)
    iterstring(s, n-1)
end

iterstring('a',10)

aaaaaaaa

aa

In [16]:
function distance(x₁, y₁, x₂, y₂)
    dx = x₂ - x₁
    dy = y₂ - y₁
    @show dx dy # 쉽게 값을 확인시켜주는 메크로

    sqrt(dx^2 + dy^2) # 함수의 반환값은 마지막으로 평가된 표현식의 값
end

function absf(x)
    if x < 0
        -x
    else
        x
    end
end

println(distance(0, 0, 3, 4))
println(absf(-3))

dx = 3
dy = 4
5.0
3


In [17]:
function isvis(x, y)
    if x % y == 0
        return true
    else
        return false
    end
    # x % y == 0 로도 가능
end

x, y = 8, 4

if isvis(x, y)
    println("x is divisible by y")
end

x is divisible by y


In [18]:
function fact(n)
    if n == 0
        1
    else
        n * fact(n-1)
    end
end

println(fact(30))
println(fact(big(30)), "\n") # Int64 보다 큰 BigInt를 불러오기 위함
# 마찬가지로 앞에 대문자가 아닌 이유는 BigInt or BigFloat를 불러오기 때문이다
# big 함수는 하나의 class에서 오는 것이 아니라 두 class도 나뉘기 때문이다
println(typeof(big(0))) # BigInt(0)
println(typeof(big(0.0))) # BigFloat(0.0)

-8764578968847253504
265252859812191058636308480000000

BigInt
BigFloat


In [19]:
function fact(n)
    if !(n isa Int64) || n < 0
        error("Wrong Input") # 이렇게 하면 Error 나고 끝남 (try - catch로 조절)
    elseif  n == 0
        1
    else
        n * fact(n-1)
    end
end

try
    println(fact(1.5))
catch
    println("Wrong Input")
end

try
    println(fact("Sans"))
catch
    println("Wrong Input")
end

println(fact(6))

Wrong Input
Wrong Input
720

### 반복

In [20]:
for i in 1:10
    if i % 3 == 0
        continue
    end
    print(i, " ")
end

1 2 4 5 7 8 10 

In [21]:
a = x = 4
ϵ = 1e-13
while true
    println(x)
    y = (x + a/x) / 2 # 뉴턴 근사
    if abs(y - x) < ϵ
        break
    end
    x = y
end

println(y)

4
2.5
2.05
2.000609756097561
2.0000000929222947
2.000000000000002
2.0


In [22]:
expr = Meta.parse("3^2/2") # 문자열을 표현식으로 변환 (println X)
println(expr)
eval(expr)

3 ^ 2 / 2


4.5

### 문자열

In [23]:
'🍌'

'🍌': Unicode U+1F34C (category So: Symbol, other)

In [24]:
fruit = "banna"
println(fruit[1]) # index at 1

b

In [19]:
fruits = "🍌!🍎 🍑"
len = length(fruits)
println(len)
fruits[len] # Julia의 문자열은 UTF-8로 가변 부호화여서 생기는 오류

# firstindex, lastindex; 바이트 문자열에 접근하는 합리적인 방법
println(fruits[firstindex(fruits)], fruits[lastindex(fruits)])

5
🍌🍑


In [26]:
println(sizeof("🍌"))
println(fruits[len])

# 값은 5여서 마지막 것을 추가하는 것처럼 보이지만, 바이트 인덱스를 건드는 것이다.
try
    println(fruits[3]) # 🍌의 3번째 index를 건드려고 하니까 Error!
catch
    println("Wrong Index")
end


index = firstindex(fruits)
while index ≤ sizeof(fruits)
    print(fruits[index], ", ")
    index = nextind(fruits, index)
end

println()

for i in fruits
    print(i, ", ")
end

4
!
Wrong Index
🍌, !, 🍎,  , 🍑, 
🍌, !, 🍎,  , 🍑, 

#### UTF-8

In [27]:
println(sizeof("👶")) # 이모지는 4바이트
println(sizeof("ض")) # 내가 잘 안쓰는 외국 언어들은 2바이트
println(sizeof("の")) # 한국어, 일본어는 3바이트
println(sizeof('👶'), "\n") # Char vs String; Char은 항상 4바이트

# 아스키 코드는 1바이트
println(sizeof("!"))
println(sizeof("a"))
println(sizeof("0"))

4
2
3
4

1
1
1


In [28]:
str = "Wow, Sans!"
println(str[6:end]) # 마지막을 표시하기 위한 예약어
println(str[2:1]) # 1 ~ end 범위 안에 있을때 앞의 값이 크면 빈 문자열
println(str[1:3]) # 무조건 숫자를 두번 써야함; Python 이랑 다름
println(str[:]) # copy 하는 기능; Python과 유사
println(str[end:-1:1]) # 거꾸로하는 방법; Python과 순서가 다름

Sans!

Wow
Wow, Sans!
!snaS ,woW

In [29]:
greet = "Hello"
whom = "World"

# 문자열 보간
println("$greet, $(whom*"!")!") # ,은 변수 이름으로 사용되지 않으니 저렇게 사용
# 저렇게 $뒤에 괄호를 사용하지 않는 것은 흔치 않음 그냥 표현이라 생각하고 사용하자
# 안에서 계산도 할 수 있다

println(Int('x')) # return Int64 (사실상 같은거지만 짧으니까 ㅎㅎ)
# ± : UTF-8 : 177번 (2바이트 : 16비트)
try
    println(Int8('±')) 
catch
    println("InexactError: trunc(Int8, 177)")
end

# 형식이 지정된 경우에는 먼저 UInt32로 변환한 다음에 trunc를 이용해서 바꾸는 듯
# Int8보다 큰 값이 들어가자 Error 

Hello, World!!
120


InexactError: trunc(Int8, 177)


In [39]:
println('a' in "sasa")
println('a' ∈ "sasa") # \in

println(!('z' in "sasa"))
println('z' ∉ "sasa") # \notin
println(occursin("sa", "sasa")) # substring
println(occursin("sasa", "sa"))

true
true
true
true
true
false

In [31]:
println('a' < 'A') # 소문자가 아스키 코드는 더 큼
println(80 == '0') # Char 끼리는 아스키로 하지만 C언어는 X
println('0' < 'a') # 아스키 순서; 0-9, A-Z, a-z

false
false
true

In [32]:
function isabc(word)
    i = firstindex(word) # i = 1
    j = nextind(word, i) 
    while j <= sizeof(word)
        if word[j] < word[i]
            return false # return 안쓰면 안됨! (함수 종료)
        end
        i = j
        j = nextind(word, i)
    end
    true
end

println(isabc("asz"))
println(isabc("mza"))

true
false

In [33]:
# 특정 개수를 출력하는 경우에 유용
fin = open("words.txt")
for _ in 1:5
    println(readline(fin))
end

aa
aah
aahed
aahing
aahs


In [34]:
# 전체를 출력하는 경우에 유용
cnt = 0
for line in eachline("words.txt")
    if cnt == 5
        break
    end
    println(line)
    cnt += 1
end

aa
aah
aahed
aahing
aahs

### 배열

In [43]:
a = [10, 20, 30, 40]
b = ["Wow", "Sans", "!!"]
c = [2022, "Sans"]
d = []

# 하나의 Type이 들어가있는 이유
println(typeof(a))
println(typeof(b))
println(typeof(c)) # 다른 Type이 존재하면 Any
println(typeof(d)) # 비어있는 배열에는 아무거나 가능하므로 Any

Vector{Int64}
Vector{String}
Vector{Any}
Vector{Any}


In [45]:
println(a[end - 1]) 
# end는 배열의 가장 마지막의 index를 정의한다
# 따라서 이와 같이 연산식을 붙이는 것이 가능하다
a[end] = 0
println(a)

30
[10, 20, 30, 0]


In [49]:
for i in eachindex(a)
    a[i] = i^2
end
println(a)
println(length(a))

[1, 4, 9, 16]
4


In [48]:
for i in [] # 빈 배열은 한번도 실행되지 않는다
    println("ㅇㅅㅇ?")
end

In [53]:
# String과 같이 slicing 가능
println(a[3:end])
println(a[2:1]) # 1 ~ end 범위 내에서는 Error 나지 않고 빈 배열 반환
println(a[end:-1:1])
println(a[:]) # 배열 복사

[9, 16]
Int64[]
[16, 9, 4, 1]


In [54]:
a[1:2] = [-1, -4] # 한번에 갱신하기 위해서 slicing을 사용 가능
println(a)

[-1, -4, 9, 16

]


In [20]:
a = [1, 2, 3, 4] .^2
b = [6, 7, 8] .^2
push!(a, 25)
println(a)

append!(a, b)

println(a) # a 뒤에 b를 붙
println(sort!(['c', 'b', 'a']))
println(sum(a))

[1, 4, 9, 16, 25]
[1, 4, 9, 16, 25, 36, 49, 64]
['a', 'b', 'c']
204


### Vector, Matrix, Array
[Julia Document; Multi-dimensional Arrays](https://docs.julialang.org/en/v1/manual/arrays/#man-multi-dim-arrays)

`; or '\n'` : vertical (1d)  
`;; or ' '` : horizontal (2d)  
`;^x` : Xd  
`,` : only list value

#### Difference of three
`vector` : N array  
`matrix` : NxM array  
`array` : NxMxO.. array

In [21]:
macro debugarr(a)
    return esc(:($println(typeof(a), ' ', size(a), '\n')))
end

# arr의 type과 size를 출력하는 macro 생성

@debugarr (macro with 1 method)

In [53]:
a = [1:9] # only list value
println(typeof(a), '\n')

a = [1:9;] # vertical => vector
println(typeof(a))
println(size(a), '\n')

a = [1;;] # horizontal => matrix (1,1)
println(typeof(a))
println(size(a))

Vector{UnitRange{Int64}}

Vector{Int64}
(9,)

Matrix{Int64}
(1, 1)


In [92]:
a = [1, 2, 3, 4, 5, 6] # 값들을 나열만 하니까 vector
@debugarr a

a = [1:6;;] # 6x1 matrix가 만들어짐
@debugarr a
# 1x6가 아닌 이유?
# [1:6;;] => [1; 2; 3; 4; 5; 6;;] 이기 때문이다
# 원래는 1d 이지만, 추가적으로 차원을 제공했다고 생각할 수 있다 (다음 셀 참고)

a = reshape(a, 6) # matrix to vector
@debugarr a

a = reshape(a, 2, 3)
@debugarr a

Vector{Int64} (6,)

Matrix{Int64} (6, 1)

Vector{Int64} (6,)

Matrix{Int64} (2, 3)


In [97]:
# ;, ' ', '\n'을 이용한 다양한 alias 표현
a = [1 2 3 4]
@debugarr a

a = [1 2 # 이러한 표현이 가능한 이유는 tab에 민감하지 않은 Julia의 특성
     3 4]
@debugarr a

a = [1; 3;; 2; 4] # ;의 우선순위는 차원이 작은 순이다
# 마지막의 ;은 생략가능하다

a = [1; 3;; 3; 4;;;]
# 하지만, ;을 생략하지 않고, 앞의 차원보다 큰 경우에는 차원이 추가된다.
# 이것을 예외 조항처럼 생각하지 말고 뒤에 크기는 같지만 아무것도 없는 행렬이 더해져서 차원이 추가된다고 생각하면 편하다.
@debugarr a

# 참고로 Array{T, 2}는 Matrix{T}와 Array{T, 1}는 Vector{T}와 같다.

Matrix{Int64} (1, 4)

Matrix{Int64} (2, 2)

Array{Int64, 3} (2, 2, 1)



In [4]:
# 이것의 연산 과정을 생각해보자
a = [zeros(Int, 2, 2) [1:2;;]
    [3 4]                  5]

a = [zeros(Int, 2, 2) [1
                       2]
     [3 4]             5]

a = [zeros(Int, 2, 2) [1
                       2]
     3 4               5]

a = [[0 0 1
      0 0 2]
      [3 4 5]]
      
a = [0 0 1; 0 0 2; 3 4 5]

3×3 Matrix{Int64}:
 0  0  1
 0  0  2
 3  4  5

In [6]:
# ' '와 '\n'은 더 높은 우선 순위를 가진다
a = [1 2 3; 4 5 6; 7 8 9;] 
# 생각해보면 우선순위가 뭔가 이상하다
a = [[1;; 2;; 3]; [4;; 5;; 6]; [7;; 8;; 9]]
# 원래는 수직으로 붙이는 것이 높은 우선순위를 가지고 있어서, 이렇게 괄호를 설정해야 하지만 원하는 결과를 얻을 수 있다.
# 따라서, 무조건적으로 먼저 실행되는 ' '와 '\n'들은 표현을 용이하게 한다.

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [20]:
# ' '와 ;;은 동시에 한 공간 안에서 사용될 수 없다
# 이유는 모르겠지만 하지말라는 건 하지말자

# a = [[1;; 2 3]; [4;; 5;; 6]; [7;; 8;; 9]]
println("""syntax: cannot mix space and ";;" separators in an array expression, except to wrap a line""")

a = [[1;; 2;; 3;;]; [4 5 6]; [7;; 8;; 9]] # 한 공간이 아니면 상관이 없다

syntax: cannot mix space and ";;" separators in an array expression, except to wrap a line


3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [83]:
# Comprehensions
x = rand(8)
y = rand(16)
x = BigFloat[0.1*x[i] + 0.4*y[i] + 0.5*y[i+1] for i=1:length(x), j=1:2:length(y)]

println(sum(x[:,1]), x[1,1], x[64])

In [87]:
# Generator Expressions
println(sum(1/n^2 for n=1:10000000))

a = map(tuple, (1/(i+j) for i=1:2, j=1:2), [1 3; 2 4])
println(a)

a = map(tuple, ((i, j) for i=1:2, j=1:2), [1:2;; 3:4])
println(a)

1.6449339668472596
[(0.5, 1) (0.3333333333333333, 3); (0.3333333333333333, 2) (0.25, 4)]
[((1, 1), 1) ((1, 2), 3); ((2, 1), 2) ((2, 2), 4)]
1.6449339668472596
[(0.5, 1) (0.3333333333333333, 3); (0.3333333333333333, 2) (0.25, 4)]
[((1, 1), 1) ((1, 2), 3); ((2, 1), 2) ((2, 2), 4)]
[((1, 2), 3), ((2, 2), 4)]


In [88]:
a = [(i,j) for i=1:3 for j=1:i if i+j == 4]
println(a)

[(2, 2), (3, 1)]


In [91]:
a = reshape([1:16;], (2, 2, 2, 2))
# [:, :, a, b]에 대해 이해해보자

2×2×2×2 Array{Int64, 4}:
[:, :, 1, 1] =
 1  3
 2  4

[:, :, 2, 1] =
 5  7
 6  8

[:, :, 1, 2] =
  9  11
 10  12

[:, :, 2, 2] =
 13  15
 14  16

In [2]:
a = rand(2,1); A = rand(2,3);

repeat(a,1,3) + A

2×3 Matrix{Float64}:
 0.857771  0.762638  0.749632
 0.398227  0.880213  0.371064

In [4]:
t = broadcast(+, a, A) # A에 a를 더해준다
println(t)
b = zeros(1,3)
t = broadcast(*, a, b) # 이것은 b가 a를 포함하지도 작동해서 2x3 행렬을 반환한다
println(t)

[0.8577713229279611 0.7626382012589625 0.7496323604243814; 0.3982267750529249 0.8802128138046924 0.3710635879399733]
[0.0 0.0 0.0; 0.0 0.0 0.0]


In [11]:
_a = Int('a')
a = [Char(_a + i) for i in 0:3] # ['a', 'b', 'c', 'd']

println(splice!(a, 2))
println(pop!(a)) # push! : 마지막 , pushfirst! : 처음
println(deleteat!(a, 1)) # splice!와 다르게 자체를 출력

b
d
['c']


In [12]:
a = [Char(_a + i) for i in 0:3] # ['a', 'b', 'c', 'd']
println(insert!(a, 2, 'x'))

['a', 'x', 'b', 'c', 'd']


In [20]:
a = [1:10;]
a = collect(1:10) # 하나씩 분류해주는 것

for i in collect("Julia")
    print(i^2)
end
println()

for i in split("I like to explain biology as chemistry and computer science")
    print(i, "  ")
end

JJuulliiaa
I  like  to  explain  biology  as  chemistry  and  computer  science

In [34]:
a = "Julia"
b = "Julia"
println(a ≡ b)

a = [1:3;]
b = [1:3;]
println(a ≡ b)

b = sort!(a) # b는 a의 별칭
println(a ≡ b)

b = sort(a)
println(a ≡ b)

true
false
true
false


### 딕셔너리

In [35]:
eng2kor = Dict()
eng2kor["one"] = "하나"
eng2kor

Dict{Any, Any} with 1 entry:
  "one" => "하나"

In [36]:
eng2kor = Dict("one" => "하나", "two" => "둘", "three" => "셋")
eng2kor

Dict{String, String} with 3 entries:
  "two"   => "둘"
  "one"   => "하나"
  "three" => "셋"

In [42]:
println(eng2kor["two"])

try
    println(eng2kor["four"])
catch
    println("""KeyError: key "four" not found""")
end

println(length(eng2kor))

둘
KeyError: key "four" not found
3

In [48]:
ks = keys(eng2kor)
vs = values(eng2kor)

println("one" ∈ ks)
println("two" ∈ ks)

println("넷" ∉ vs)

true
true
true


In [50]:
println(get(eng2kor, "four", "몰?루")) # 모른 경우 기본 값을 설정해줄 수 있다
# 역조회 할 바에 dict를 두개 만들자
# dict는 해쉬 테이블이여서 O(1)이라고 하니 걍 두개 쓰자

몰?루

In [5]:
import Pkg; Pkg.add("BenchmarkTools")

    Updating registry at `C:\Users\Ryu\.julia\registries\General.toml`
   Resolving package versions...
  No Changes to `C:\Users\Ryu\.julia\environments\v1.7\Project.toml`
  No Changes to `C:\Users\Ryu\.julia\environments\v1.7\Manifest.toml`


In [11]:
# dict의 빠른 속도를 이용해서 굳이 메모리를 낭비하지 않고도, 메모이제이션을 할 수 있다.
using BenchmarkTools

known = Dict(0=>0, 1=>1)
function fi(n::BigInt) # 자료편 명시를 통한 속도 증가
    if n ∈ keys(known)
        return known[n]
    end
    res = fi(n - 1) + fi(n - 2)
    known[n] = res # 전역변수를 서술하지 않아도, 값의 수정은 문제가 없지만 직접적인 수정은 문제가 된다
    res
end

@benchmark fi(BigInt(1000))

BenchmarkTools.Trial: 10000 samples with 723 evaluations.
 Range (min … max):  176.902 ns … 219.433 μs  ┊ GC (min … max):  0.00% … 87.02%
 Time  (median):     195.159 ns               ┊ GC (median):     0.00%
 Time  (mean ± σ):   532.723 ns ±   6.841 μs  ┊ GC (mean ± σ):  49.47% ±  3.87%

        ▁███▅▃   ▁▁                                              
  ▁▂▂▃▃▅███████▇███▇▆▄▄▃▂▂▂▂▂▂▂▂▂▂▂▃▃▃▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁ ▃
  177 ns           Histogram: frequency by time          269 ns <

 Memory estimate: 152 bytes, allocs estimate: 8.

In [12]:
# 지역변수와 전역변수
tot_che = false

function che()
    tot_che = true # 전역변수에 아무런 영향을 미치지 못한다
end

che()
println(tot_che)

false


In [13]:
tot_che = false

function che()
    global tot_che = true # 전역변수로 따로 불러내야 한다
end

che()
println(tot_che)

true

### 튜플

In [22]:
a = 1, 2, 3
a = (1, 2, 3)
a = tuple(1, 2, 3)
a = (1,) # 괄호 없애면 터짐
a = tuple(1:10...) # 뒤에서 자세히 서술

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [40]:
# 배열이랑 거의 비슷함
a = tuple(1:10...)
println(a[end:-1:1])

# 하지면 불변이여서 값 안바뀜
# a[1] = -1 # MethodError: no method matching setindex!
println((1, 2, 3) < (-1, 100)) # 순서대로 값 비교

a, b = 1, 2
a, b = b, a # 값 바꾸기
println(a, ' ', b)

(10, 9, 8, 7, 6, 5, 4, 3, 2, 1)
false
2 1


In [46]:
a = divrem(7, 3)
println(join(a, " "))

i, j = a
println(i, ' ', j)

2 1
2 1


In [52]:
function sumstring(args...)
    join(args)
end

println(sumstring("ㅇㅅㅇ", "~!"))

a = 2, 7
println(join(divrem(a...), " "))

ㅇㅅㅇ~!
0 2


In [61]:
_a = Int('a')

a = [Char(_a + i) for i in 0:2]
b = [1:3;]
for (i, j) in zip(a, b)
    println(i, ' ', j)
end
println()

a = [Char(_a + i) for i in 19:22]
b = [20:23;]
for pair in zip(a, b)
    println(pair[1], ' ', pair[2])
end

a 1
b 2
c 3

t 20
u 21
v 22
w 23


In [63]:
d = Dict('a'=>1, 'b'=>2, 'c'=>3, 'd'=>4)

for (k, v) in d
    println(k, ' ', v) # 순서는 랜덤임
end

a 1
c 3
d 4
b 2

In [64]:
t = [('a', 1), ('b', 2), ('c', 3)]
d = Dict(t)

Dict{Char, Int64} with 3 entries:
  'a' => 1
  'c' => 3
  'b' => 2

In [65]:
d = Dict(zip("abc", 1:3))

Dict{Char, Int64} with 3 entries:
  'a' => 1
  'c' => 3
  'b' => 2

In [66]:
# 연산자 오버로딩
import Base.+ # 지역범위로 추가시키는 기능

function +(a::String, b::String)
    a * b
end

"ab" + "cd" 
# 이렇게 추가로 연산자의 가능을 추가함

"abcd"

In [74]:
a = 150
println(a % 2 == 0 ? "even" : "odd")

even


## 빠른 코드를 위한 규칙

[Julia Document; Performance Tips](https://docs.julialang.org/en/v1/manual/performance-tips/)

In [84]:
Threads.nthreads()

1

## 멀티 쓰레딩
[Julia Document; Multi-Threading](https://docs.julialang.org/en/v1/manual/multi-threading/)